[package]
name = "responses-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for the responses crate"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }